---
title: "dashboard_dvf"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen=999)

library(flexdashboard)
library(dplyr)
library(lubridate)
library(plotly)
library(leaflet)
library(geojsonio)
library(raster)
```

```{r include=FALSE}
dvf<-read.csv2("dvf_propre.geocoded.csv",sep=";")

dvf<-dvf %>% 
  mutate(Date_mutation_d=dmy(Date_mutation), 
  Code_departement=sprintf("%02d", Code_departement)
  )%>% 
  mutate( periode=format(Date_mutation_d,"%Y%m"))

kpi1<-dvf %>% filter(year(Date_mutation_d)=="2019") %>% count 
kpi2<-dvf %>% filter(year(Date_mutation_d)=="2019" & Type_local=="Appartement") %>% summarize(prix_m2_mean=round(mean(prix_m2),0))
kpi3<-dvf %>% filter(year(Date_mutation_d)=="2019" & Type_local=="Maison") %>% summarize(prix_m2_mean=round(mean(prix_m2),0))

```

Page 1
===================================== 

Row
-----------------------------------------------------------------------

### Nb de ventes 2019

```{r echo=FALSE}
valueBox(kpi1,icon="fa-hands-helping")
```

### Prix m2 Appartement

```{r echo=FALSE}
valueBox(paste0(kpi2," €"),icon="fa-building")
```

### Prix m2 Maison

```{r echo=FALSE}
valueBox(paste0(kpi3," €"),icon="fa-home")
```


Row
-----------------------------------------------------------------------
### Ventes mensuelles
```{r echo=FALSE}
dvf %>% group_by(periode) %>% summarise(n=n()) %>% 
    plot_ly(x = ~periode, y = ~n, type='scatter',mode = 'lines')%>%
  layout(yaxis = list(range = c(0, 8000)))

```

### Répartition maison / appartement
```{r echo=FALSE}
dvf %>% 
  group_by(periode,Type_local) %>%
  summarise(n=n()) %>% 
    plot_ly(x = ~periode, y = ~n,type='bar',color=~Type_local)
```


Page 2
===================================== 
```{r include=FALSE}
#data prep for carto
dpt <- geojsonio::geojson_read("./departements.geojson", what = "sp")
prix_m2.dpt<-dvf %>% group_by(Code_departement) %>% summarize(prix_m2_mean=mean(prix_m2))

dpt.plus.prixm2 <- raster::merge(dpt, prix_m2.dpt, by.x="code", by.y="Code_departement")

bins <- c(0,1000,1500,2000,2500, 10000, Inf)
pal <- colorBin("YlOrRd", domain =dpt.plus.prixm2$prix_m2_mean , bins = bins)

labels <- sprintf(
  "<strong>%s</strong><br/>%g €/m<sup>2</sup>",
  dpt.plus.prixm2$code, round(dpt.plus.prixm2$prix_m2_mean,0)
) %>% lapply(htmltools::HTML)
```

```{r echo=FALSE}
leaflet(data=dpt.plus.prixm2) %>% 
  addPolygons(
    fillColor = ~pal(prix_m2_mean),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    label = labels)

```

Page 3
===================================== 

```{r echo = FALSE}
data<-dvf %>% filter(Code_departement=="79") %>% dplyr::select(latitude,longitude,Valeur_fonciere,Type_local)

bins <- c(0,50000,100000,125000,150000, 300000, Inf)
pal <- colorBin("YlOrRd", domain =dpt.plus.prixm2$prix_m2_mean , bins = bins)

leaflet(data) %>% addTiles() %>%
  addCircleMarkers(~as.numeric(longitude), ~as.numeric(latitude), 
                   label=~as.character(paste0(Type_local," / prix : ",Valeur_fonciere,"€")),
                   color = ~pal(Valeur_fonciere))

```

